package com.ksusha.weather.utils

const val API_KEY = "b21f4e61c974429f84a152622220110"
const val FORECAST = "forecast"
const val FORECASTDAY = "forecastday"
const val LOCATION = "location"
const val NAME = "name"
const val DATE = "date"
const val DAY = "day"
const val CONDITION = "condition"
const val TEXT = "text"
const val MAXTEMP_C = "maxtemp_c"
const val MINTEMP_C = "mintemp_c"
const val ICON = "icon"
const val CURRENT = "current"
const val LAST_UPDATED = "last_updated"
const val TEMP_C = "temp_c"
const val HOURS = "24 HOURS"
const val DAYS = "7 DAYS"
const val HOUR = "hour"
const val TIME = "time"